spring.application.name=tracker

spring.datasource.url=jdbc:postgresql://db:5432/tracker_database
spring.datasource.username=user_dev
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret=tracker-api-jwt-secret-key-2026-secure
security.jwt.issuer=com.example.tracker
security.jwt.expiration-ms=3600000
